os:
  - linux
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
install:
    - mvn clean install
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
